### PR TITLE
Fix bad pr

### PR DESCRIPTION
**Pull request by nlisgo**
I'm submitting a fix for the bad css.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
I think you mean

``` scss
// bad css
```

Or possibly

``` scss
/* bad css */
```

But either way that bad CSS is intentional, to demonstrate Travis does indeed fail - so it needn't be fixed :-)

**Comment by nlisgo** [comment]
I'm using your example project as an example in a presentation next week.

I'm not expecting you to merge in my pull request but I wanted to demonstrate a Travis CI pull request passing.

Would it put you out if I sent another pull request? Again, I'm not expecting it to be merged in :)

**Comment by matthew-andrews** [comment]
Oh no feel free.  Where will the presentation be?  Might be interested in attending...

**Comment by nlisgo** [comment]
http://2014.drupalcampyorkshire.co.uk/

**Comment by nlisgo** [comment]
Actually it's this weekend, in Leeds.

**Comment by matthew-andrews** [comment]
Ahh that's a shame.  Anyway, feel free to raise as many PRs as you like.  (If you don't mind closing them off when you're done that would be great - but no need to do that immediately, it can wait until after this weekend)

**Comment by nlisgo** [comment]
I will be giving the presentation again at Drupalcambs next month and may submit it for Drupalcon Amsterdam in September.

Thanks for submitting this example repo.

**Comment by nlisgo** [comment]
I will upload my slides at some point and be sure to credit you.

**Pull request closed without merging**
